[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_API_BASE_URL = "https://your-backend.onrender.com/api"
  VITE_STRIPE_PUBLISHABLE_KEY = "pk_test_your_stripe_publishable_key_here"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
